version: "3.9"
   
services:

  db:
    image: postgres    
    env_file:
      - .docker.env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: app-database
        target: /var/lib/postgresql/data

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - .docker.env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  app-database:
    name: app-database